In [1]:
import numpy as np
x=np.zeros(3)
x

array([0., 0., 0.])

In [2]:
x.shape

(3,)

In [6]:
x.shape=(3,1)
x

array([[0.],
       [0.],
       [0.]])

In [10]:
a=np.linspace(2,10,4)
a

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

In [11]:
z=np.array([1,2,3,4])
z

array([1, 2, 3, 4])

In [13]:
m=np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
k=np.array([3,6,4,9,7,8])
np.sort(k)

array([3, 4, 6, 7, 8, 9])

In [21]:
b=np.array([1,2,3])
bk=np.concatenate((b,np.sort(k)))
bk

array([1, 2, 3, 3, 4, 6, 7, 8, 9])

In [26]:
bk.shape=(3,3)
bk

array([[1, 2, 3],
       [3, 4, 6],
       [7, 8, 9]])

In [28]:
r=np.random.randint(10,size=2)
r

array([3, 8])

In [38]:
import pandas as pd
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]}
l= [i for i in range(1,4)]
v=pd.DataFrame(mydataset,index=l)
v

cars  passings
1    BMW         3
2  Volvo         7
3   Ford         2

In [30]:
a=[1,2,3]
pd.Series(a)

0    1
1    2
2    3
dtype: int64

In [31]:
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

day1    420
day2    380
day3    390
dtype: int64
